#!/usr/bin/env python3
"""Refresh the automatic change log in HANDOVER.md from git history.

Runs from the post-commit hook (.githooks/post-commit, enabled by tools/install_hooks.sh), so every commit
is recorded in the handover without anyone having to remember. Safe to run by hand at any time:

    python3 tools/update_handover.py          # rewrite the section
    python3 tools/update_handover.py --check  # exit 1 if the section is out of date
"""
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
HANDOVER = ROOT / 'HANDOVER.md'
START, END = '<!-- AUTO-LOG:START -->', '<!-- AUTO-LOG:END -->'
LIMIT = 80


def git(*args):
    return subprocess.run(['git', *args], cwd=ROOT, capture_output=True, text=True, check=True).stdout


def build_section():
    raw = git('log', f'-n{LIMIT}', '--date=short', '--shortstat', '--pretty=format:%x1e%ad%x1f%s')
    rows = []
    for chunk in raw.split('\x1e'):
        chunk = chunk.strip()
        if not chunk:
            continue
        head, _, stat = chunk.partition('\n')
        date, _, subject = head.partition('\x1f')
        files = ''
        stat = stat.strip()
        if stat:
            files = stat.split(' file')[0].strip()
        subject = subject.replace('|', '\\|')
        rows.append(f'| {date} | {subject} | {files} |')
    total = git('rev-list', '--count', 'HEAD').strip()
    lines = [
        START,
        f'_Generated by `tools/update_handover.py` from git history ({total} commits in total, newest first, last {min(LIMIT, len(rows))} shown). Do not edit by hand._',
        '',
        '| Date | Change | Files |',
        '|---|---|---|',
        *rows,
        END,
    ]
    return '\n'.join(lines)


def main():
    text = HANDOVER.read_text(encoding='utf-8')
    if START not in text or END not in text:
        print('HANDOVER.md has no AUTO-LOG markers', file=sys.stderr)
        return 1
    before, rest = text.split(START, 1)
    _, after = rest.split(END, 1)
    section = build_section()
    new = before + section + after
    if '--check' in sys.argv:
        if new != text:
            print('HANDOVER.md change log is out of date: run python3 tools/update_handover.py', file=sys.stderr)
            return 1
        return 0
    if new != text:
        HANDOVER.write_text(new, encoding='utf-8')
    return 0


if __name__ == '__main__':
    sys.exit(main())
